/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 * This file was generated by the script `scripts/generateNamespaces.ts` on 2024-03-27 20:10:15.
 * Changes to this file may be overwritten by subsequent generation.
 */
export enum Namespaces {
  NUM_81 = "81",
  NUM_163 = "163",
  NUM_591 = "591",
  NUM_2048 = "2048",
  NUM_8264 = "8264",
  NUM_12306 = "12306",
  NUM_0818TUAN = "0818tuan",
  NUM_141JAV = "141jav",
  NUM_141PPV = "141ppv",
  NUM_18COMIC = "18comic",
  NUM_19LOU = "19lou",
  NUM_1LOU = "1lou",
  NUM_1POINT3ACRES = "1point3acres",
  NUM_1X = "1x",
  NUM_2023GAME = "2023game",
  NUM_2CYCD = "2cycd",
  NUM_36KR = "36kr",
  NUM_3DMGAME = "3dmgame",
  NUM_3KNS = "3kns",
  NUM_423DOWN = "423down",
  NUM_4GAMERS = "4gamers",
  NUM_4KSJ = "4ksj",
  NUM_500PX = "500px",
  NUM_50FORUM = "50forum",
  NUM_52HRTT = "52hrtt",
  NUM_56KOG = "56kog",
  NUM_5EPLAY = "5eplay",
  NUM_6PARK = "6park",
  NUM_6V123 = "6v123",
  NUM_78DM = "78dm",
  NUM_7MMTV = "7mmtv",
  NUM_8KCOS = "8kcos",
  NUM_8WORLD = "8world",
  NUM_91PORN = "91porn",
  NUM_95MM = "95mm",
  NUM_9TO5 = "9to5",
  A9VG = "a9vg",
  AAMACAU = "aamacau",
  ABC = "abc",
  ABMEDIA = "abmedia",
  ABSKOOP = "abskoop",
  ACFUN = "acfun",
  ACG17 = "acg17",
  ACPAA = "acpaa",
  ACS = "acs",
  AEAWEB = "aeaweb",
  AEON = "aeon",
  AFDIAN = "afdian",
  AGEFANS = "agefans",
  AGIRLS = "agirls",
  AGORA0 = "agora0",
  AHJZU = "ahjzu",
  AICAIJING = "aicaijing",
  AIEA = "aiea",
  AIJISHU = "aijishu",
  AINVEST = "ainvest",
  AIP = "aip",
  AIRCHINA = "airchina",
  AISIXIANG = "aisixiang",
  AJMIDE = "ajmide",
  ALIRESEARCH = "aliresearch",
  ALISTAPART = "alistapart",
  ALIYUN = "aliyun",
  ALJAZEERA = "aljazeera",
  ALLY = "ally",
  ALTERNATIVETO = "alternativeto",
  AMAZON = "amazon",
  ANDROID = "android",
  ANNUALREVIEWS = "annualreviews",
  ANQUANKE = "anquanke",
  APACHE = "apache",
  APISEVEN = "apiseven",
  APKPURE = "apkpure",
  APNEWS = "apnews",
  NUM_APP_CENTER = "app-center",
  APPLE = "apple",
  APPLEINSIDER = "appleinsider",
  APPSTORE = "appstore",
  APPSTORRENT = "appstorrent",
  AQARA = "aqara",
  ARCTERYX = "arcteryx",
  ARKNIGHTS = "arknights",
  ARTSTATION = "artstation",
  ASIANTOLICK = "asiantolick",
  ASUS = "asus",
  ATCODER = "atcoder",
  NUM_AUTO_STATS = "auto-stats",
  BAAI = "baai",
  BACKLINKO = "backlinko",
  BAD = "bad",
  BAIDU = "baidu",
  BANDCAMP = "bandcamp",
  BANGUMI = "bangumi",
  BAOZIMH = "baozimh",
  BARRONSCHINA = "barronschina",
  BAST = "bast",
  BBC = "bbc",
  BBCNEWSLABS = "bbcnewslabs",
  BDYS = "bdys",
  BEHANCE = "behance",
  BELLROY = "bellroy",
  BENDIBAO = "bendibao",
  BGMLIST = "bgmlist",
  BIGQUANT = "bigquant",
  BILIBILI = "bilibili",
  BING = "bing",
  BIODISCOVER = "biodiscover",
  BIOONE = "bioone",
  BIQUGE = "biquge",
  BIT = "bit",
  BITBUCKET = "bitbucket",
  BITMOVIN = "bitmovin",
  BJFU = "bjfu",
  BJP = "bjp",
  BJSK = "bjsk",
  BJWXDXH = "bjwxdxh",
  BJX = "bjx",
  BLIZZARD = "blizzard",
  BLOGREAD = "blogread",
  BLOOMBERG = "bloomberg",
  BLUESTACKS = "bluestacks",
  BMKG = "bmkg",
  BNU = "bnu",
  BOC = "boc",
  BOOKFERE = "bookfere",
  BOORU = "booru",
  BOSSDESIGN = "bossdesign",
  BRAVE = "brave",
  BROOKLYNMUSEUM = "brooklynmuseum",
  BSE = "bse",
  BSKY = "bsky",
  BTZJ = "btzj",
  BUAA = "buaa",
  BULIANGLIN = "bulianglin",
  BUPT = "bupt",
  BYTECLICKS = "byteclicks",
  BYTES = "bytes",
  C114 = "c114",
  CAAI = "caai",
  CAAM = "caam",
  CAAREVIEWS = "caareviews",
  CAHKMS = "cahkms",
  CAIJING = "caijing",
  CAIXIN = "caixin",
  CAIXINGLOBAL = "caixinglobal",
  CAMCHINA = "camchina",
  CANKAOXIAOXI = "cankaoxiaoxi",
  CARTOONMAD = "cartoonmad",
  CAS = "cas",
  CASSSP = "casssp",
  CAST = "cast",
  CAU = "cau",
  CAUS = "caus",
  CBAIGUI = "cbaigui",
  CBC = "cbc",
  CBIRC = "cbirc",
  CBNWEEK = "cbnweek",
  CCAC = "ccac",
  CCF = "ccf",
  CCNU = "ccnu",
  CCREPORTS = "ccreports",
  CCTV = "cctv",
  CDE = "cde",
  CDI = "cdi",
  CDZJRYB = "cdzjryb",
  CEBBANK = "cebbank",
  CFACHINA = "cfachina",
  CFMMC = "cfmmc",
  CGTN = "cgtn",
  CHAINCATCHER = "chaincatcher",
  CHANGBA = "changba",
  CHAOXING = "chaoxing",
  CHAPING = "chaping",
  CHICULTURE = "chiculture",
  CHINA = "china",
  CHINADEGREES = "chinadegrees",
  CHINAFACTCHECK = "chinafactcheck",
  CHINAISA = "chinaisa",
  CHINAMONEY = "chinamoney",
  CHINANEWS = "chinanews",
  CHINATHINKTANKS = "chinathinktanks",
  CHINAVENTURE = "chinaventure",
  CHINAWRITER = "chinawriter",
  CHSI = "chsi",
  CHUANLIU = "chuanliu",
  CIB = "cib",
  CIIDBNU = "ciidbnu",
  CIVITAI = "civitai",
  CIWEIMAO = "ciweimao",
  CLICKME = "clickme",
  CLOUDNATIVE = "cloudnative",
  CLS = "cls",
  CMA = "cma",
  CMDE = "cmde",
  CMPXCHG8B = "cmpxchg8b",
  NUM_CN_HEALTHCARE = "cn-healthcare",
  CNA = "cna",
  CNBC = "cnbc",
  CNBETA = "cnbeta",
  CNBLOGS = "cnblogs",
  CNCF = "cncf",
  CNEB = "cneb",
  CNGAL = "cngal",
  CNJXOL = "cnjxol",
  CNKI = "cnki",
  CNLJXH = "cnljxh",
  CNTHEORY = "cntheory",
  CNTV = "cntv",
  CODEFORCES = "codeforces",
  COINDESK = "coindesk",
  COMICAT = "comicat",
  COMICSKINGDOM = "comicskingdom",
  CONSUMER = "consumer",
  COOL18 = "cool18",
  COOLAPK = "coolapk",
  COOMER = "coomer",
  COPYMANGA = "copymanga",
  CPCEY = "cpcey",
  CPUID = "cpuid",
  CQGAS = "cqgas",
  CQWU = "cqwu",
  CRAC = "crac",
  NUM_CREATIVE_COMIC = "creative-comic",
  CROSSBELL = "crossbell",
  CS = "cs",
  CSDN = "csdn",
  CSSN = "cssn",
  CSTE = "cste",
  CSU = "csu",
  CTS = "cts",
  CUC = "cuc",
  CURIOUSCAT = "curiouscat",
  CURIUS = "curius",
  CW = "cw",
  CYZONE = "cyzone",
  CZTV = "cztv",
  DAHECUBE = "dahecube",
  DAILY = "daily",
  DAMAI = "damai",
  DAPENTI = "dapenti",
  DARWINAWARDS = "darwinawards",
  DAYANZAI = "dayanzai",
  DBAPLUS = "dbaplus",
  DBLP = "dblp",
  DCARD = "dcard",
  DCFEVER = "dcfever",
  DDOSI = "ddosi",
  DEADLINE = "deadline",
  DEDAO = "dedao",
  DEEPLEARNING = "deeplearning",
  DEEPMIND = "deepmind",
  DEFAULT = "default",
  DELTAIO = "deltaio",
  DEVOLVERDIGITAL = "devolverdigital",
  DGJYW = "dgjyw",
  DHU = "dhu",
  DIANDONG = "diandong",
  DIERSHOUBING = "diershoubing",
  DISCORD = "discord",
  DISCOURSE = "discourse",
  DISCUZ = "discuz",
  DISINFO = "disinfo",
  DISKANALYZER = "diskanalyzer",
  DISTILL = "distill",
  DLNEWS = "dlnews",
  DLSITE = "dlsite",
  DMZJ = "dmzj",
  DN = "dn",
  DNAINDIA = "dnaindia",
  DOCKERHUB = "dockerhub",
  DOCSCHINA = "docschina",
  DOL = "dol",
  DOMP4 = "domp4",
  DONGQIUDI = "dongqiudi",
  DOROHEDORO = "dorohedoro",
  DOUBAN = "douban",
  DOUYIN = "douyin",
  DOUYU = "douyu",
  DRIBBBLE = "dribbble",
  DTCJ = "dtcj",
  DUOZHUAYU = "duozhuayu",
  DUSHU = "dushu",
  DUT = "dut",
  DX2025 = "dx2025",
  DXY = "dxy",
  NUM_E_HENTAI = "e-hentai",
  EAGLE = "eagle",
  EARTHQUAKE = "earthquake",
  EASTDAY = "eastday",
  EASTMONEY = "eastmoney",
  ECNU = "ecnu",
  ECONOMIST = "economist",
  ECUST = "ecust",
  EGSEA = "egsea",
  EHENTAI = "ehentai",
  EKANTIPUR = "ekantipur",
  NUM_ELASTICSEARCH_CN = "elasticsearch-cn",
  ELEDUCK = "eleduck",
  ELSEVIER = "elsevier",
  EMBASSY = "embassy",
  EPICGAMES = "epicgames",
  EPRICE = "eprice",
  EVENTERNOTE = "eventernote",
  NUM_F_DROID = "f-droid",
  FAMITSU = "famitsu",
  FANSLY = "fansly",
  FANTIA = "fantia",
  FANXINZHUI = "fanxinzhui",
  FARMATTERS = "farmatters",
  FASTBULL = "fastbull",
  FDA = "fda",
  FENG = "feng",
  FF14 = "ff14",
  FFFDM = "fffdm",
  FINOLOGY = "finology",
  FINVIZ = "finviz",
  FIRECORE = "firecore",
  FIREFOX = "firefox",
  NUM_FISHER_SPB = "fisher-spb",
  FISHSHELL = "fishshell",
  FJKSBM = "fjksbm",
  FLYERT = "flyert",
  FOCUSTAIWAN = "focustaiwan",
  FOLLOWIN = "followin",
  FORESIGHTNEWS = "foresightnews",
  FOREVERBLOG = "foreverblog",
  FORTNITE = "fortnite",
  FORTUNECHINA = "fortunechina",
  FOSSHUB = "fosshub",
  FREE = "free",
  FREEBUF = "freebuf",
  FREECOMPUTERBOOKS = "freecomputerbooks",
  FREEWECHAT = "freewechat",
  FT = "ft",
  FULIBA = "fuliba",
  FURSTAR = "furstar",
  FUTUNN = "futunn",
  NUM_FX_MARKETS = "fx-markets",
  FX678 = "fx678",
  FXIAOKE = "fxiaoke",
  FZMTR = "fzmtr",
  GAMEAPPS = "gameapps",
  GAMEBASE = "gamebase",
  GAMEGENE = "gamegene",
  GAMER = "gamer",
  GAMER520 = "gamer520",
  GAMERSECRET = "gamersecret",
  GAMME = "gamme",
  GCORES = "gcores",
  GDSRX = "gdsrx",
  GDUT = "gdut",
  GELONGHUI = "gelonghui",
  GEOCACHING = "geocaching",
  GETDR = "getdr",
  GETITFREE = "getitfree",
  GETTR = "gettr",
  NUM_GF_CN = "gf-cn",
  GIHYO = "gihyo",
  GITEE = "gitee",
  GITHUB = "github",
  GITPOD = "gitpod",
  GLOBALLAWREVIEW = "globallawreview",
  GOCN = "gocn",
  GOFANS = "gofans",
  GOGOANIMEHD = "gogoanimehd",
  GOOGLE = "google",
  GOV = "gov",
  GREASYFORK = "greasyfork",
  GRIST = "grist",
  GRUBSTREET = "grubstreet",
  GUANCHA = "guancha",
  GUANGDIU = "guangdiu",
  GUANGZHOUMETRO = "guangzhoumetro",
  GUANHAI = "guanhai",
  GUDUODATA = "guduodata",
  GUMROAD = "gumroad",
  GUOKR = "guokr",
  GXMZU = "gxmzu",
  GZDAILY = "gzdaily",
  GZHU = "gzhu",
  HACKERNEWS = "hackernews",
  HACKERTALK = "hackertalk",
  HACKING8 = "hacking8",
  HACKMD = "hackmd",
  HACKYOURNEWS = "hackyournews",
  HAFU = "hafu",
  HAKKATV = "hakkatv",
  HAMELN = "hameln",
  HARVARD = "harvard",
  HASHNODE = "hashnode",
  HBOOKER = "hbooker",
  HBR = "hbr",
  HDU = "hdu",
  HEBTV = "hebtv",
  HELLOBTC = "hellobtc",
  HELLOGITHUB = "hellogithub",
  NUM_HEX_RAYS = "hex-rays",
  HICAIRO = "hicairo",
  HINATAZAKA46 = "hinatazaka46",
  HIT = "hit",
  HITSZ = "hitsz",
  HITWH = "hitwh",
  HIZU = "hizu",
  HK01 = "hk01",
  HKEJ = "hkej",
  HKEPC = "hkepc",
  HKET = "hket",
  HKJUNKCALL = "hkjunkcall",
  HLJUCM = "hljucm",
  HNRB = "hnrb",
  HNU = "hnu",
  HONGKONG = "hongkong",
  HOSTMONIT = "hostmonit",
  HOTUKDEALS = "hotukdeals",
  HOUXU = "houxu",
  HOWTOFORGE = "howtoforge",
  HOYOLAB = "hoyolab",
  HPOI = "hpoi",
  HRBEU = "hrbeu",
  HRBUST = "hrbust",
  HUANQIU = "huanqiu",
  HUGGINGFACE = "huggingface",
  HUNANPEA = "hunanpea",
  HUNAU = "hunau",
  HUOXIAN = "huoxian",
  HUPU = "hupu",
  HUST = "hust",
  HUXIU = "huxiu",
  IANSPRIGGS = "ianspriggs",
  ICAC = "icac",
  ICBC = "icbc",
  IDAILY = "idaily",
  IDOLYPRIDE = "idolypride",
  IEEE = "ieee",
  NUM_IEEE_SECURITY = "ieee-security",
  IELTS = "ielts",
  IFENG = "ifeng",
  NUM_IFI_AUDIO = "ifi-audio",
  IGUOGUO = "iguoguo",
  IIILAB = "iiilab",
  IKEA = "ikea",
  IMAGEMAGICK = "imagemagick",
  IMIKER = "imiker",
  INDIANSINKUWAIT = "indiansinkuwait",
  INDIENOVA = "indienova",
  INEWSWEEK = "inewsweek",
  INFOQ = "infoq",
  INFORMS = "informs",
  INFZM = "infzm",
  INOREADER = "inoreader",
  INSTAGRAM = "instagram",
  INSTRUCTABLES = "instructables",
  IPPA = "ippa",
  IPSW = "ipsw",
  IQILU = "iqilu",
  IQIYI = "iqiyi",
  IQNEW = "iqnew",
  IRESEARCH = "iresearch",
  ISSUEHUNT = "issuehunt",
  ITCH = "itch",
  ITHOME = "ithome",
  IWARA = "iwara",
  IXIGUA = "ixigua",
  JANDAN = "jandan",
  JAPANPOST = "japanpost",
  JAVBUS = "javbus",
  JAVDB = "javdb",
  JAVLIBRARY = "javlibrary",
  JD = "jd",
  JEWISHMUSEUM = "jewishmuseum",
  JIANSHU = "jianshu",
  JIAOLIUDAO = "jiaoliudao",
  JIEMIAN = "jiemian",
  JIKE = "jike",
  JIN10 = "jin10",
  JINSE = "jinse",
  JISILU = "jisilu",
  JJWXC = "jjwxc",
  JORNADA = "jornada",
  JOU = "jou",
  JPXGMN = "jpxgmn",
  JSEEA = "jseea",
  JSU = "jsu",
  JUEJIN = "juejin",
  JUMP = "jump",
  JUNHE = "junhe",
  NUM_KAMEN_RIDER_OFFICIAL = "kamen-rider-official",
  KANTARWORLDPANEL = "kantarworldpanel",
  KAOPU = "kaopu",
  KBS = "kbs",
  KCNA = "kcna",
  KE = "ke",
  KEEP = "keep",
  KEEPASS = "keepass",
  KEMONO = "kemono",
  KEPU = "kepu",
  KEYLOL = "keylol",
  KIMLAW = "kimlaw",
  KONGHQ = "konghq",
  KUAIDI100 = "kuaidi100",
  KUNCHENGBLOG = "kunchengblog",
  KUWAITLOCAL = "kuwaitlocal",
  KYODONEWS = "kyodonews",
  LAIMANHUA = "laimanhua",
  LALA = "lala",
  LANG = "lang",
  LANQIAO = "lanqiao",
  LAOHU8 = "laohu8",
  LATEPOST = "latepost",
  LAYOFFS = "layoffs",
  LEARNBLOCKCHAIN = "learnblockchain",
  LEARNKU = "learnku",
  LEETCODE = "leetcode",
  LEIPHONE = "leiphone",
  LEMMY = "lemmy",
  LFSYD = "lfsyd",
  LIFEWEEK = "lifeweek",
  LIGHTNOVEL = "lightnovel",
  LINE = "line",
  LINKEDIN = "linkedin",
  LINKRESEARCHER = "linkresearcher",
  LINOVELIB = "linovelib",
  LIQUIPEDIA = "liquipedia",
  LITEROTICA = "literotica",
  LIULINBLOG = "liulinblog",
  LIVEUAMAP = "liveuamap",
  LKONG = "lkong",
  LOFTER = "lofter",
  LOGCLUB = "logclub",
  LOGONEWS = "logonews",
  LOLTW = "loltw",
  LOONGARCH = "loongarch",
  NUM_LOVELIVE_ANIME = "lovelive-anime",
  LSNU = "lsnu",
  LUOGU = "luogu",
  LUXIANGDONG = "luxiangdong",
  LVV2 = "lvv2",
  LXIXSXA = "lxixsxa",
  M4 = "m4",
  MACFILOS = "macfilos",
  MACMENUBAR = "macmenubar",
  MACUPDATE = "macupdate",
  MAGAZINELIB = "magazinelib",
  MAIL = "mail",
  MANGADEX = "mangadex",
  MANHUAGUI = "manhuagui",
  MASTODON = "mastodon",
  MCKINSEY = "mckinsey",
  MDPI = "mdpi",
  NUM_MEDIEVAL_CHINA = "medieval-china",
  MEDIUM = "medium",
  MEDSCI = "medsci",
  METACRITIC = "metacritic",
  METEOR = "meteor",
  METMUSEUM = "metmuseum",
  MI = "mi",
  MICROSOFT = "microsoft",
  MIHOYO = "mihoyo",
  MINDMEISTER = "mindmeister",
  MINECRAFT = "minecraft",
  MINGPAO = "mingpao",
  MINIFLUX = "miniflux",
  MIRROR = "mirror",
  MISSAV = "missav",
  MISSKEY = "misskey",
  MITTRCHINA = "mittrchina",
  MIUI = "miui",
  MIXCLOUD = "mixcloud",
  MODB = "modb",
  MODELSCOPE = "modelscope",
  MODIAN = "modian",
  MODRINTH = "modrinth",
  MOHW = "mohw",
  MOX = "mox",
  MPAYPASS = "mpaypass",
  MRDX = "mrdx",
  MRM = "mrm",
  MVM = "mvm",
  MYDRIVERS = "mydrivers",
  MYFIGURECOLLECTION = "myfigurecollection",
  MYGOPEN = "mygopen",
  MYMUSICSHEET = "mymusicsheet",
  MYSQL = "mysql",
  NASA = "nasa",
  NATGEO = "natgeo",
  NATIONALGEOGRAPHIC = "nationalgeographic",
  NATURE = "nature",
  NAUTIL = "nautil",
  NBD = "nbd",
  NBER = "nber",
  NUM_NCC_CMA = "ncc-cma",
  NCEPU = "ncepu",
  NCU = "ncu",
  NCWU = "ncwu",
  NUM_NDSS_SYMPOSIUM = "ndss-symposium",
  NEATDOWNLOADMANAGER = "neatdownloadmanager",
  NEEA = "neea",
  NENU = "nenu",
  NETFLAV = "netflav",
  NEU = "neu",
  NEWMUSEUM = "newmuseum",
  NEWRANK = "newrank",
  NEWS = "news",
  NEWSMARKET = "newsmarket",
  NEWZMZ = "newzmz",
  NEXTAPPLE = "nextapple",
  NGA = "nga",
  NGOCN2 = "ngocn2",
  NHENTAI = "nhentai",
  NHK = "nhk",
  NIAOGEBIJI = "niaogebiji",
  NIFD = "nifd",
  NIKKEI = "nikkei",
  NINTENDO = "nintendo",
  NIPPON = "nippon",
  NJGLYY = "njglyy",
  NJIT = "njit",
  NJNU = "njnu",
  NJU = "nju",
  NJUCM = "njucm",
  NJUPT = "njupt",
  NJUST = "njust",
  NJXZC = "njxzc",
  NLC = "nlc",
  NLTIMES = "nltimes",
  NMC = "nmc",
  NMTV = "nmtv",
  NODEJS = "nodejs",
  NOGIZAKA46 = "nogizaka46",
  NOSEC = "nosec",
  NOTATESLAAPP = "notateslaapp",
  NOTEFOLIO = "notefolio",
  NOTION = "notion",
  NOW = "now",
  NOWCODER = "nowcoder",
  NPM = "npm",
  NPR = "npr",
  NTDM = "ntdm",
  NTDTV = "ntdtv",
  NUA = "nua",
  NUAA = "nuaa",
  NUIST = "nuist",
  NWAFU = "nwafu",
  NYAA = "nyaa",
  NYTIMES = "nytimes",
  OCEANENGINE = "oceanengine",
  ODAILY = "odaily",
  OEEEE = "oeeee",
  OILCHEM = "oilchem",
  ONCC = "oncc",
  ONEHU = "onehu",
  ONET = "onet",
  NUM_OO_SOFTWARE = "oo-software",
  OPENAI = "openai",
  OPENWRT = "openwrt",
  ORCID = "orcid",
  ORENO3D = "oreno3d",
  OSCHINA = "oschina",
  OSHWHUB = "oshwhub",
  OSU = "osu",
  OTOBANANA = "otobanana",
  OUC = "ouc",
  OUP = "oup",
  OUTAGEREPORT = "outagereport",
  PANEWSLAB = "panewslab",
  PAPERS = "papers",
  PARADIGM = "paradigm",
  PARLIAMENT = "parliament",
  PATAGONIA = "patagonia",
  PAULGRAHAM = "paulgraham",
  NUM_PENGUIN_RANDOM_HOUSE = "penguin-random-house",
  PEOPLE = "people",
  PEOPO = "peopo",
  PHORONIX = "phoronix",
  PIANYIVPS = "pianyivps",
  PIANYUAN = "pianyuan",
  PICNOB = "picnob",
  PICUKI = "picuki",
  PIKABU = "pikabu",
  PINCONG = "pincong",
  PINGWEST = "pingwest",
  PIXABAY = "pixabay",
  PIXIV = "pixiv",
  PIYAO = "piyao",
  PKMER = "pkmer",
  PKU = "pku",
  PLAYNO1 = "playno1",
  PLAYPCESOR = "playpcesor",
  PLURK = "plurk",
  PNAS = "pnas",
  PORNHUB = "pornhub",
  POSTMAN = "postman",
  NUM_PRICONNE_REDIVE = "priconne-redive",
  PRODUCTHUNT = "producthunt",
  PS = "ps",
  PTS = "pts",
  PUBMED = "pubmed",
  PUMC = "pumc",
  PUTTY = "putty",
  PWC = "pwc",
  QBITAI = "qbitai",
  QBITTORRENT = "qbittorrent",
  QDU = "qdu",
  QIANP = "qianp",
  QIANZHAN = "qianzhan",
  QIDIAN = "qidian",
  QINGTING = "qingting",
  QIPAMAIJIA = "qipamaijia",
  QIYOUJIAGE = "qiyoujiage",
  QLU = "qlu",
  QM120 = "qm120",
  NUM_QOO_APP = "qoo-app",
  QQ = "qq",
  QQ88 = "qq88",
  QQORW = "qqorw",
  QUESTMOBILE = "questmobile",
  QUICKER = "quicker",
  QUST = "qust",
  QWEATHER = "qweather",
  RADIO = "radio",
  NUM_RADIO_CANADA = "radio-canada",
  RAREHISTORICALPHOTOS = "rarehistoricalphotos",
  RATTIBHA = "rattibha",
  RAWKUMA = "rawkuma",
  REACTIFLUX = "reactiflux",
  REACTNEWSLETTER = "reactnewsletter",
  READHUB = "readhub",
  REMNOTE = "remnote",
  RESEARCHGATE = "researchgate",
  REUTERS = "reuters",
  RFA = "rfa",
  RFI = "rfi",
  RIGHT = "right",
  RODONG = "rodong",
  ROUTLEDGE = "routledge",
  RSC = "rsc",
  RSSHUB = "rsshub",
  RUANCAN = "ruancan",
  RUC = "ruc",
  RUNTRAIL = "runtrail",
  RUSTCC = "rustcc",
  SAKURAZAKA46 = "sakurazaka46",
  SAMSUNG = "samsung",
  SARABA1ST = "saraba1st",
  SASS = "sass",
  SCAU = "scau",
  SCIENCE = "science",
  SCIENCEDIRECT = "sciencedirect",
  SCIENCENET = "sciencenet",
  SCMP = "scmp",
  SCNU = "scnu",
  SCTV = "sctv",
  SCUT = "scut",
  SCVTC = "scvtc",
  SDU = "sdu",
  SDUST = "sdust",
  SDZK = "sdzk",
  NUM_SEC_IN = "sec-in",
  NUM_SEC_WIKI = "sec-wiki",
  SECRSS = "secrss",
  SEEKINGALPHA = "seekingalpha",
  SEGA = "sega",
  SEGMENTFAULT = "segmentfault",
  SEHUATANG = "sehuatang",
  SENSORTOWER = "sensortower",
  SETN = "setn",
  SEU = "seu",
  SFACG = "sfacg",
  SHCSTHEATRE = "shcstheatre",
  SHIEP = "shiep",
  SHISU = "shisu",
  SHMEEA = "shmeea",
  SHMTU = "shmtu",
  SHOAC = "shoac",
  SHOPBACK = "shopback",
  SHOPPINGDESIGN = "shoppingdesign",
  SHOWSTART = "showstart",
  SHU = "shu",
  SHUIGUOPAI = "shuiguopai",
  SICAU = "sicau",
  SIGSAC = "sigsac",
  SIMPLEINFO = "simpleinfo",
  SINA = "sina",
  SINCHEW = "sinchew",
  SIS001 = "sis001",
  SJTU = "sjtu",
  SKYSPORTS = "skysports",
  SLOWMIST = "slowmist",
  SMASHINGMAGAZINE = "smashingmagazine",
  SMZDM = "smzdm",
  SNOWPEAK = "snowpeak",
  SOBOOKS = "sobooks",
  SOGOU = "sogou",
  SOHU = "sohu",
  SOLIDOT = "solidot",
  SONY = "sony",
  SOUNDOFHOPE = "soundofhope",
  SOURCEFORGE = "sourceforge",
  SOUTHCN = "southcn",
  SPOTIFY = "spotify",
  SPRINGER = "springer",
  SPUTNIKNEWS = "sputniknews",
  SQMC = "sqmc",
  SSE = "sse",
  SSM = "ssm",
  SSPAI = "sspai",
  SSPU = "sspu",
  STARTUPLATTE = "startuplatte",
  STBU = "stbu",
  STCN = "stcn",
  STDAILY = "stdaily",
  STEAM = "steam",
  STHEADLINE = "stheadline",
  STOCKEDGE = "stockedge",
  STORM = "storm",
  STORYFM = "storyfm",
  STRATECHERY = "stratechery",
  STUDYGOLANG = "studygolang",
  SUBHD = "subhd",
  SUPCHINA = "supchina",
  SURFSHARK = "surfshark",
  SUSTECH = "sustech",
  SWISSINFO = "swissinfo",
  SWJTU = "swjtu",
  SWPU = "swpu",
  SYOSETU = "syosetu",
  SYSU = "sysu",
  SZSE = "szse",
  SZU = "szu",
  T66Y = "t66y",
  TABLEAU = "tableau",
  TAIWANNEWS = "taiwannews",
  TANGSHUFANG = "tangshufang",
  TAOBAO = "taobao",
  TAOGUBA = "taoguba",
  TAPTAP = "taptap",
  TASS = "tass",
  TECHCRUNCH = "techcrunch",
  TECHFLOWPOST = "techflowpost",
  TECHPOWERUP = "techpowerup",
  TELECOMPAPER = "telecompaper",
  TELEGRAM = "telegram",
  TENCENT = "tencent",
  TESLA = "tesla",
  TEST = "test",
  NUM_TFC_TAIWAN = "tfc-taiwan",
  TGBUS = "tgbus",
  THEATLANTIC = "theatlantic",
  THEBLOCKBEATS = "theblockbeats",
  THECATCITY = "thecatcity",
  THECOVER = "thecover",
  THEHINDU = "thehindu",
  THEINITIUM = "theinitium",
  THEMOVIEDB = "themoviedb",
  THENEWSLENS = "thenewslens",
  THEPAPER = "thepaper",
  THEVERGE = "theverge",
  THOUGHTCO = "thoughtco",
  THREADS = "threads",
  THWIKI = "thwiki",
  TIKTOK = "tiktok",
  TIMEDNEWS = "timednews",
  TINGSHUITZ = "tingshuitz",
  TINGTINGFM = "tingtingfm",
  TISI = "tisi",
  TJU = "tju",
  TOKENINSIGHT = "tokeninsight",
  TONGJI = "tongji",
  TONGLI = "tongli",
  TOODAYLAB = "toodaylab",
  TOPHUB = "tophub",
  TOPYS = "topys",
  TRADINGVIEW = "tradingview",
  TRANSCRIPTFOREST = "transcriptforest",
  TRENDING = "trending",
  TRENDINGPAPERS = "trendingpapers",
  TRIBALFOOTBALL = "tribalfootball",
  TROW = "trow",
  TVB = "tvb",
  TVTROPES = "tvtropes",
  TWITCH = "twitch",
  TWITTER = "twitter",
  TWREPORTER = "twreporter",
  TXRJY = "txrjy",
  TYNU = "tynu",
  TYPORA = "typora",
  U3C3 = "u3c3",
  U9A9 = "u9a9",
  UBER = "uber",
  UCAS = "ucas",
  UCHICAGO = "uchicago",
  UDN = "udn",
  UESTC = "uestc",
  UIBE = "uibe",
  ULAPIA = "ulapia",
  UNIQLO = "uniqlo",
  UNRAID = "unraid",
  UNUSUALWHALES = "unusualwhales",
  UPC = "upc",
  UPTIMEROBOT = "uptimerobot",
  NUM_URAAKA_JOSHI = "uraaka-joshi",
  URBANDICTIONARY = "urbandictionary",
  USENIX = "usenix",
  USEPANDA = "usepanda",
  USTB = "ustb",
  USTC = "ustc",
  USTS = "usts",
  UTGD = "utgd",
  UW = "uw",
  V1TX = "v1tx",
  V2EX = "v2ex",
  V2RAYSHARE = "v2rayshare",
  NUM_VCB_S = "vcb-s",
  VERFGHBW = "verfghbw",
  VIMEO = "vimeo",
  VOCUS = "vocus",
  VOM = "vom",
  WALLHAVEN = "wallhaven",
  WALLPAPERHUB = "wallpaperhub",
  WALLSTREETCN = "wallstreetcn",
  WANQU = "wanqu",
  WARTHUNDER = "warthunder",
  WDC = "wdc",
  WEB = "web",
  WEB3CAFF = "web3caff",
  WECHAT = "wechat",
  WEEKENDHK = "weekendhk",
  WEIBO = "weibo",
  WENKU8 = "wenku8",
  WFDF = "wfdf",
  WFU = "wfu",
  WHITEHOUSE = "whitehouse",
  WHO = "who",
  WHU = "whu",
  WIKINEWS = "wikinews",
  WINSTALL = "winstall",
  WISE = "wise",
  WIZFILE = "wizfile",
  NUM_WMC_BJ = "wmc-bj",
  WMPVP = "wmpvp",
  WNACG = "wnacg",
  WORLDJOURNAL = "worldjournal",
  WOSHIPM = "woshipm",
  WSJ = "wsj",
  WSYU = "wsyu",
  WTU = "wtu",
  WYZXWK = "wyzxwk",
  WZU = "wzu",
  NUM_X_MOL = "x-mol",
  X6D = "x6d",
  XAUFE = "xaufe",
  XAUT = "xaut",
  XBOXFAN = "xboxfan",
  XIAOHEIHE = "xiaoheihe",
  XIAOHONGSHU = "xiaohongshu",
  XIAOMIYOUPIN = "xiaomiyoupin",
  XIAOTE = "xiaote",
  XIAOYUZHOU = "xiaoyuzhou",
  XIAOZHUANLAN = "xiaozhuanlan",
  XIDIAN = "xidian",
  XIMALAYA = "ximalaya",
  XINPIANCHANG = "xinpianchang",
  XJTU = "xjtu",
  XKB = "xkb",
  XMANHUA = "xmanhua",
  XMNN = "xmnn",
  XMUT = "xmut",
  XSIJISHE = "xsijishe",
  XUEQIU = "xueqiu",
  XUNHUPAY = "xunhupay",
  XYS = "xys",
  XYZRANK = "xyzrank",
  YAHOO = "yahoo",
  YANGTZEU = "yangtzeu",
  YCWB = "ycwb",
  YGKKK = "ygkkk",
  YICAI = "yicai",
  YMGAL = "ymgal",
  NUM_YOASOBI_MUSIC = "yoasobi-music",
  YOMIURI = "yomiuri",
  YOMUJP = "yomujp",
  YOUKU = "youku",
  YOUTUBE = "youtube",
  YOUZHIYOUXING = "youzhiyouxing",
  YUQUE = "yuque",
  YXDOWN = "yxdown",
  YXDZQB = "yxdzqb",
  YXRB = "yxrb",
  YYETS = "yyets",
  YYSTV = "yystv",
  ZAGG = "zagg",
  ZAKER = "zaker",
  ZAOBAO = "zaobao",
  ZAOZAO = "zaozao",
  ZCMU = "zcmu",
  ZCOOL = "zcool",
  ZHIBO8 = "zhibo8",
  ZHIHU = "zhihu",
  ZHITONGCAIJING = "zhitongcaijing",
  ZHIY = "zhiy",
  ZHUBAI = "zhubai",
  ZHUJICEPING = "zhujiceping",
  ZHUWANG = "zhuwang",
  ZIMUXIA = "zimuxia",
  ZJGTJY = "zjgtjy",
  ZJOL = "zjol",
  ZJU = "zju",
  ZJUT = "zjut",
  ZJUVAG = "zjuvag",
  ZODGAME = "zodgame",
  ZOTERO = "zotero",
  ZRBLOG = "zrblog",
  ZUEL = "zuel",
  ZUVIO = "zuvio",
  ZYSHOW = "zyshow",
  ZYW = "zyw",
}

export type Namespace =
  | "81"
  | "163"
  | "591"
  | "2048"
  | "8264"
  | "12306"
  | "0818tuan"
  | "141jav"
  | "141ppv"
  | "18comic"
  | "19lou"
  | "1lou"
  | "1point3acres"
  | "1x"
  | "2023game"
  | "2cycd"
  | "36kr"
  | "3dmgame"
  | "3kns"
  | "423down"
  | "4gamers"
  | "4ksj"
  | "500px"
  | "50forum"
  | "52hrtt"
  | "56kog"
  | "5eplay"
  | "6park"
  | "6v123"
  | "78dm"
  | "7mmtv"
  | "8kcos"
  | "8world"
  | "91porn"
  | "95mm"
  | "9to5"
  | "a9vg"
  | "aamacau"
  | "abc"
  | "abmedia"
  | "abskoop"
  | "acfun"
  | "acg17"
  | "acpaa"
  | "acs"
  | "aeaweb"
  | "aeon"
  | "afdian"
  | "agefans"
  | "agirls"
  | "agora0"
  | "ahjzu"
  | "aicaijing"
  | "aiea"
  | "aijishu"
  | "ainvest"
  | "aip"
  | "airchina"
  | "aisixiang"
  | "ajmide"
  | "aliresearch"
  | "alistapart"
  | "aliyun"
  | "aljazeera"
  | "ally"
  | "alternativeto"
  | "amazon"
  | "android"
  | "annualreviews"
  | "anquanke"
  | "apache"
  | "apiseven"
  | "apkpure"
  | "apnews"
  | "app-center"
  | "apple"
  | "appleinsider"
  | "appstore"
  | "appstorrent"
  | "aqara"
  | "arcteryx"
  | "arknights"
  | "artstation"
  | "asiantolick"
  | "asus"
  | "atcoder"
  | "auto-stats"
  | "baai"
  | "backlinko"
  | "bad"
  | "baidu"
  | "bandcamp"
  | "bangumi"
  | "baozimh"
  | "barronschina"
  | "bast"
  | "bbc"
  | "bbcnewslabs"
  | "bdys"
  | "behance"
  | "bellroy"
  | "bendibao"
  | "bgmlist"
  | "bigquant"
  | "bilibili"
  | "bing"
  | "biodiscover"
  | "bioone"
  | "biquge"
  | "bit"
  | "bitbucket"
  | "bitmovin"
  | "bjfu"
  | "bjp"
  | "bjsk"
  | "bjwxdxh"
  | "bjx"
  | "blizzard"
  | "blogread"
  | "bloomberg"
  | "bluestacks"
  | "bmkg"
  | "bnu"
  | "boc"
  | "bookfere"
  | "booru"
  | "bossdesign"
  | "brave"
  | "brooklynmuseum"
  | "bse"
  | "bsky"
  | "btzj"
  | "buaa"
  | "bulianglin"
  | "bupt"
  | "byteclicks"
  | "bytes"
  | "c114"
  | "caai"
  | "caam"
  | "caareviews"
  | "cahkms"
  | "caijing"
  | "caixin"
  | "caixinglobal"
  | "camchina"
  | "cankaoxiaoxi"
  | "cartoonmad"
  | "cas"
  | "casssp"
  | "cast"
  | "cau"
  | "caus"
  | "cbaigui"
  | "cbc"
  | "cbirc"
  | "cbnweek"
  | "ccac"
  | "ccf"
  | "ccnu"
  | "ccreports"
  | "cctv"
  | "cde"
  | "cdi"
  | "cdzjryb"
  | "cebbank"
  | "cfachina"
  | "cfmmc"
  | "cgtn"
  | "chaincatcher"
  | "changba"
  | "chaoxing"
  | "chaping"
  | "chiculture"
  | "china"
  | "chinadegrees"
  | "chinafactcheck"
  | "chinaisa"
  | "chinamoney"
  | "chinanews"
  | "chinathinktanks"
  | "chinaventure"
  | "chinawriter"
  | "chsi"
  | "chuanliu"
  | "cib"
  | "ciidbnu"
  | "civitai"
  | "ciweimao"
  | "clickme"
  | "cloudnative"
  | "cls"
  | "cma"
  | "cmde"
  | "cmpxchg8b"
  | "cn-healthcare"
  | "cna"
  | "cnbc"
  | "cnbeta"
  | "cnblogs"
  | "cncf"
  | "cneb"
  | "cngal"
  | "cnjxol"
  | "cnki"
  | "cnljxh"
  | "cntheory"
  | "cntv"
  | "codeforces"
  | "coindesk"
  | "comicat"
  | "comicskingdom"
  | "consumer"
  | "cool18"
  | "coolapk"
  | "coomer"
  | "copymanga"
  | "cpcey"
  | "cpuid"
  | "cqgas"
  | "cqwu"
  | "crac"
  | "creative-comic"
  | "crossbell"
  | "cs"
  | "csdn"
  | "cssn"
  | "cste"
  | "csu"
  | "cts"
  | "cuc"
  | "curiouscat"
  | "curius"
  | "cw"
  | "cyzone"
  | "cztv"
  | "dahecube"
  | "daily"
  | "damai"
  | "dapenti"
  | "darwinawards"
  | "dayanzai"
  | "dbaplus"
  | "dblp"
  | "dcard"
  | "dcfever"
  | "ddosi"
  | "deadline"
  | "dedao"
  | "deeplearning"
  | "deepmind"
  | "default"
  | "deltaio"
  | "devolverdigital"
  | "dgjyw"
  | "dhu"
  | "diandong"
  | "diershoubing"
  | "discord"
  | "discourse"
  | "discuz"
  | "disinfo"
  | "diskanalyzer"
  | "distill"
  | "dlnews"
  | "dlsite"
  | "dmzj"
  | "dn"
  | "dnaindia"
  | "dockerhub"
  | "docschina"
  | "dol"
  | "domp4"
  | "dongqiudi"
  | "dorohedoro"
  | "douban"
  | "douyin"
  | "douyu"
  | "dribbble"
  | "dtcj"
  | "duozhuayu"
  | "dushu"
  | "dut"
  | "dx2025"
  | "dxy"
  | "e-hentai"
  | "eagle"
  | "earthquake"
  | "eastday"
  | "eastmoney"
  | "ecnu"
  | "economist"
  | "ecust"
  | "egsea"
  | "ehentai"
  | "ekantipur"
  | "elasticsearch-cn"
  | "eleduck"
  | "elsevier"
  | "embassy"
  | "epicgames"
  | "eprice"
  | "eventernote"
  | "f-droid"
  | "famitsu"
  | "fansly"
  | "fantia"
  | "fanxinzhui"
  | "farmatters"
  | "fastbull"
  | "fda"
  | "feng"
  | "ff14"
  | "fffdm"
  | "finology"
  | "finviz"
  | "firecore"
  | "firefox"
  | "fisher-spb"
  | "fishshell"
  | "fjksbm"
  | "flyert"
  | "focustaiwan"
  | "followin"
  | "foresightnews"
  | "foreverblog"
  | "fortnite"
  | "fortunechina"
  | "fosshub"
  | "free"
  | "freebuf"
  | "freecomputerbooks"
  | "freewechat"
  | "ft"
  | "fuliba"
  | "furstar"
  | "futunn"
  | "fx-markets"
  | "fx678"
  | "fxiaoke"
  | "fzmtr"
  | "gameapps"
  | "gamebase"
  | "gamegene"
  | "gamer"
  | "gamer520"
  | "gamersecret"
  | "gamme"
  | "gcores"
  | "gdsrx"
  | "gdut"
  | "gelonghui"
  | "geocaching"
  | "getdr"
  | "getitfree"
  | "gettr"
  | "gf-cn"
  | "gihyo"
  | "gitee"
  | "github"
  | "gitpod"
  | "globallawreview"
  | "gocn"
  | "gofans"
  | "gogoanimehd"
  | "google"
  | "gov"
  | "greasyfork"
  | "grist"
  | "grubstreet"
  | "guancha"
  | "guangdiu"
  | "guangzhoumetro"
  | "guanhai"
  | "guduodata"
  | "gumroad"
  | "guokr"
  | "gxmzu"
  | "gzdaily"
  | "gzhu"
  | "hackernews"
  | "hackertalk"
  | "hacking8"
  | "hackmd"
  | "hackyournews"
  | "hafu"
  | "hakkatv"
  | "hameln"
  | "harvard"
  | "hashnode"
  | "hbooker"
  | "hbr"
  | "hdu"
  | "hebtv"
  | "hellobtc"
  | "hellogithub"
  | "hex-rays"
  | "hicairo"
  | "hinatazaka46"
  | "hit"
  | "hitsz"
  | "hitwh"
  | "hizu"
  | "hk01"
  | "hkej"
  | "hkepc"
  | "hket"
  | "hkjunkcall"
  | "hljucm"
  | "hnrb"
  | "hnu"
  | "hongkong"
  | "hostmonit"
  | "hotukdeals"
  | "houxu"
  | "howtoforge"
  | "hoyolab"
  | "hpoi"
  | "hrbeu"
  | "hrbust"
  | "huanqiu"
  | "huggingface"
  | "hunanpea"
  | "hunau"
  | "huoxian"
  | "hupu"
  | "hust"
  | "huxiu"
  | "ianspriggs"
  | "icac"
  | "icbc"
  | "idaily"
  | "idolypride"
  | "ieee"
  | "ieee-security"
  | "ielts"
  | "ifeng"
  | "ifi-audio"
  | "iguoguo"
  | "iiilab"
  | "ikea"
  | "imagemagick"
  | "imiker"
  | "indiansinkuwait"
  | "indienova"
  | "inewsweek"
  | "infoq"
  | "informs"
  | "infzm"
  | "inoreader"
  | "instagram"
  | "instructables"
  | "ippa"
  | "ipsw"
  | "iqilu"
  | "iqiyi"
  | "iqnew"
  | "iresearch"
  | "issuehunt"
  | "itch"
  | "ithome"
  | "iwara"
  | "ixigua"
  | "jandan"
  | "japanpost"
  | "javbus"
  | "javdb"
  | "javlibrary"
  | "jd"
  | "jewishmuseum"
  | "jianshu"
  | "jiaoliudao"
  | "jiemian"
  | "jike"
  | "jin10"
  | "jinse"
  | "jisilu"
  | "jjwxc"
  | "jornada"
  | "jou"
  | "jpxgmn"
  | "jseea"
  | "jsu"
  | "juejin"
  | "jump"
  | "junhe"
  | "kamen-rider-official"
  | "kantarworldpanel"
  | "kaopu"
  | "kbs"
  | "kcna"
  | "ke"
  | "keep"
  | "keepass"
  | "kemono"
  | "kepu"
  | "keylol"
  | "kimlaw"
  | "konghq"
  | "kuaidi100"
  | "kunchengblog"
  | "kuwaitlocal"
  | "kyodonews"
  | "laimanhua"
  | "lala"
  | "lang"
  | "lanqiao"
  | "laohu8"
  | "latepost"
  | "layoffs"
  | "learnblockchain"
  | "learnku"
  | "leetcode"
  | "leiphone"
  | "lemmy"
  | "lfsyd"
  | "lifeweek"
  | "lightnovel"
  | "line"
  | "linkedin"
  | "linkresearcher"
  | "linovelib"
  | "liquipedia"
  | "literotica"
  | "liulinblog"
  | "liveuamap"
  | "lkong"
  | "lofter"
  | "logclub"
  | "logonews"
  | "loltw"
  | "loongarch"
  | "lovelive-anime"
  | "lsnu"
  | "luogu"
  | "luxiangdong"
  | "lvv2"
  | "lxixsxa"
  | "m4"
  | "macfilos"
  | "macmenubar"
  | "macupdate"
  | "magazinelib"
  | "mail"
  | "mangadex"
  | "manhuagui"
  | "mastodon"
  | "mckinsey"
  | "mdpi"
  | "medieval-china"
  | "medium"
  | "medsci"
  | "metacritic"
  | "meteor"
  | "metmuseum"
  | "mi"
  | "microsoft"
  | "mihoyo"
  | "mindmeister"
  | "minecraft"
  | "mingpao"
  | "miniflux"
  | "mirror"
  | "missav"
  | "misskey"
  | "mittrchina"
  | "miui"
  | "mixcloud"
  | "modb"
  | "modelscope"
  | "modian"
  | "modrinth"
  | "mohw"
  | "mox"
  | "mpaypass"
  | "mrdx"
  | "mrm"
  | "mvm"
  | "mydrivers"
  | "myfigurecollection"
  | "mygopen"
  | "mymusicsheet"
  | "mysql"
  | "nasa"
  | "natgeo"
  | "nationalgeographic"
  | "nature"
  | "nautil"
  | "nbd"
  | "nber"
  | "ncc-cma"
  | "ncepu"
  | "ncu"
  | "ncwu"
  | "ndss-symposium"
  | "neatdownloadmanager"
  | "neea"
  | "nenu"
  | "netflav"
  | "neu"
  | "newmuseum"
  | "newrank"
  | "news"
  | "newsmarket"
  | "newzmz"
  | "nextapple"
  | "nga"
  | "ngocn2"
  | "nhentai"
  | "nhk"
  | "niaogebiji"
  | "nifd"
  | "nikkei"
  | "nintendo"
  | "nippon"
  | "njglyy"
  | "njit"
  | "njnu"
  | "nju"
  | "njucm"
  | "njupt"
  | "njust"
  | "njxzc"
  | "nlc"
  | "nltimes"
  | "nmc"
  | "nmtv"
  | "nodejs"
  | "nogizaka46"
  | "nosec"
  | "notateslaapp"
  | "notefolio"
  | "notion"
  | "now"
  | "nowcoder"
  | "npm"
  | "npr"
  | "ntdm"
  | "ntdtv"
  | "nua"
  | "nuaa"
  | "nuist"
  | "nwafu"
  | "nyaa"
  | "nytimes"
  | "oceanengine"
  | "odaily"
  | "oeeee"
  | "oilchem"
  | "oncc"
  | "onehu"
  | "onet"
  | "oo-software"
  | "openai"
  | "openwrt"
  | "orcid"
  | "oreno3d"
  | "oschina"
  | "oshwhub"
  | "osu"
  | "otobanana"
  | "ouc"
  | "oup"
  | "outagereport"
  | "panewslab"
  | "papers"
  | "paradigm"
  | "parliament"
  | "patagonia"
  | "paulgraham"
  | "penguin-random-house"
  | "people"
  | "peopo"
  | "phoronix"
  | "pianyivps"
  | "pianyuan"
  | "picnob"
  | "picuki"
  | "pikabu"
  | "pincong"
  | "pingwest"
  | "pixabay"
  | "pixiv"
  | "piyao"
  | "pkmer"
  | "pku"
  | "playno1"
  | "playpcesor"
  | "plurk"
  | "pnas"
  | "pornhub"
  | "postman"
  | "priconne-redive"
  | "producthunt"
  | "ps"
  | "pts"
  | "pubmed"
  | "pumc"
  | "putty"
  | "pwc"
  | "qbitai"
  | "qbittorrent"
  | "qdu"
  | "qianp"
  | "qianzhan"
  | "qidian"
  | "qingting"
  | "qipamaijia"
  | "qiyoujiage"
  | "qlu"
  | "qm120"
  | "qoo-app"
  | "qq"
  | "qq88"
  | "qqorw"
  | "questmobile"
  | "quicker"
  | "qust"
  | "qweather"
  | "radio"
  | "radio-canada"
  | "rarehistoricalphotos"
  | "rattibha"
  | "rawkuma"
  | "reactiflux"
  | "reactnewsletter"
  | "readhub"
  | "remnote"
  | "researchgate"
  | "reuters"
  | "rfa"
  | "rfi"
  | "right"
  | "rodong"
  | "routledge"
  | "rsc"
  | "rsshub"
  | "ruancan"
  | "ruc"
  | "runtrail"
  | "rustcc"
  | "sakurazaka46"
  | "samsung"
  | "saraba1st"
  | "sass"
  | "scau"
  | "science"
  | "sciencedirect"
  | "sciencenet"
  | "scmp"
  | "scnu"
  | "sctv"
  | "scut"
  | "scvtc"
  | "sdu"
  | "sdust"
  | "sdzk"
  | "sec-in"
  | "sec-wiki"
  | "secrss"
  | "seekingalpha"
  | "sega"
  | "segmentfault"
  | "sehuatang"
  | "sensortower"
  | "setn"
  | "seu"
  | "sfacg"
  | "shcstheatre"
  | "shiep"
  | "shisu"
  | "shmeea"
  | "shmtu"
  | "shoac"
  | "shopback"
  | "shoppingdesign"
  | "showstart"
  | "shu"
  | "shuiguopai"
  | "sicau"
  | "sigsac"
  | "simpleinfo"
  | "sina"
  | "sinchew"
  | "sis001"
  | "sjtu"
  | "skysports"
  | "slowmist"
  | "smashingmagazine"
  | "smzdm"
  | "snowpeak"
  | "sobooks"
  | "sogou"
  | "sohu"
  | "solidot"
  | "sony"
  | "soundofhope"
  | "sourceforge"
  | "southcn"
  | "spotify"
  | "springer"
  | "sputniknews"
  | "sqmc"
  | "sse"
  | "ssm"
  | "sspai"
  | "sspu"
  | "startuplatte"
  | "stbu"
  | "stcn"
  | "stdaily"
  | "steam"
  | "stheadline"
  | "stockedge"
  | "storm"
  | "storyfm"
  | "stratechery"
  | "studygolang"
  | "subhd"
  | "supchina"
  | "surfshark"
  | "sustech"
  | "swissinfo"
  | "swjtu"
  | "swpu"
  | "syosetu"
  | "sysu"
  | "szse"
  | "szu"
  | "t66y"
  | "tableau"
  | "taiwannews"
  | "tangshufang"
  | "taobao"
  | "taoguba"
  | "taptap"
  | "tass"
  | "techcrunch"
  | "techflowpost"
  | "techpowerup"
  | "telecompaper"
  | "telegram"
  | "tencent"
  | "tesla"
  | "test"
  | "tfc-taiwan"
  | "tgbus"
  | "theatlantic"
  | "theblockbeats"
  | "thecatcity"
  | "thecover"
  | "thehindu"
  | "theinitium"
  | "themoviedb"
  | "thenewslens"
  | "thepaper"
  | "theverge"
  | "thoughtco"
  | "threads"
  | "thwiki"
  | "tiktok"
  | "timednews"
  | "tingshuitz"
  | "tingtingfm"
  | "tisi"
  | "tju"
  | "tokeninsight"
  | "tongji"
  | "tongli"
  | "toodaylab"
  | "tophub"
  | "topys"
  | "tradingview"
  | "transcriptforest"
  | "trending"
  | "trendingpapers"
  | "tribalfootball"
  | "trow"
  | "tvb"
  | "tvtropes"
  | "twitch"
  | "twitter"
  | "twreporter"
  | "txrjy"
  | "tynu"
  | "typora"
  | "u3c3"
  | "u9a9"
  | "uber"
  | "ucas"
  | "uchicago"
  | "udn"
  | "uestc"
  | "uibe"
  | "ulapia"
  | "uniqlo"
  | "unraid"
  | "unusualwhales"
  | "upc"
  | "uptimerobot"
  | "uraaka-joshi"
  | "urbandictionary"
  | "usenix"
  | "usepanda"
  | "ustb"
  | "ustc"
  | "usts"
  | "utgd"
  | "uw"
  | "v1tx"
  | "v2ex"
  | "v2rayshare"
  | "vcb-s"
  | "verfghbw"
  | "vimeo"
  | "vocus"
  | "vom"
  | "wallhaven"
  | "wallpaperhub"
  | "wallstreetcn"
  | "wanqu"
  | "warthunder"
  | "wdc"
  | "web"
  | "web3caff"
  | "wechat"
  | "weekendhk"
  | "weibo"
  | "wenku8"
  | "wfdf"
  | "wfu"
  | "whitehouse"
  | "who"
  | "whu"
  | "wikinews"
  | "winstall"
  | "wise"
  | "wizfile"
  | "wmc-bj"
  | "wmpvp"
  | "wnacg"
  | "worldjournal"
  | "woshipm"
  | "wsj"
  | "wsyu"
  | "wtu"
  | "wyzxwk"
  | "wzu"
  | "x-mol"
  | "x6d"
  | "xaufe"
  | "xaut"
  | "xboxfan"
  | "xiaoheihe"
  | "xiaohongshu"
  | "xiaomiyoupin"
  | "xiaote"
  | "xiaoyuzhou"
  | "xiaozhuanlan"
  | "xidian"
  | "ximalaya"
  | "xinpianchang"
  | "xjtu"
  | "xkb"
  | "xmanhua"
  | "xmnn"
  | "xmut"
  | "xsijishe"
  | "xueqiu"
  | "xunhupay"
  | "xys"
  | "xyzrank"
  | "yahoo"
  | "yangtzeu"
  | "ycwb"
  | "ygkkk"
  | "yicai"
  | "ymgal"
  | "yoasobi-music"
  | "yomiuri"
  | "yomujp"
  | "youku"
  | "youtube"
  | "youzhiyouxing"
  | "yuque"
  | "yxdown"
  | "yxdzqb"
  | "yxrb"
  | "yyets"
  | "yystv"
  | "zagg"
  | "zaker"
  | "zaobao"
  | "zaozao"
  | "zcmu"
  | "zcool"
  | "zhibo8"
  | "zhihu"
  | "zhitongcaijing"
  | "zhiy"
  | "zhubai"
  | "zhujiceping"
  | "zhuwang"
  | "zimuxia"
  | "zjgtjy"
  | "zjol"
  | "zju"
  | "zjut"
  | "zjuvag"
  | "zodgame"
  | "zotero"
  | "zrblog"
  | "zuel"
  | "zuvio"
  | "zyshow"
  | "zyw";

export enum Categories {
  GAME = "game",
  NEW_MEDIA = "new-media",
  MULTIMEDIA = "multimedia",
  STUDY = "study",
  OTHER = "other",
  BBS = "bbs",
  TRAVEL = "travel",
  SHOPPING = "shopping",
  ANIME = "anime",
  DESIGN = "design",
  PICTURE = "picture",
  READING = "reading",
  TRADITIONAL_MEDIA = "traditional-media",
  JOURNAL = "journal",
  UNIVERSITY = "university",
  PROGRAMMING = "programming",
  FINANCE = "finance",
  PROGRAM_UPDATE = "program-update",
  BLOG = "blog",
  SOCIAL_MEDIA = "social-media",
  LIVE = "live",
  GOVERNMENT = "government",
  FORECAST = "forecast",
}

export type Category =
  | "game"
  | "new-media"
  | "multimedia"
  | "study"
  | "other"
  | "bbs"
  | "travel"
  | "shopping"
  | "anime"
  | "design"
  | "picture"
  | "reading"
  | "traditional-media"
  | "journal"
  | "university"
  | "programming"
  | "finance"
  | "program-update"
  | "blog"
  | "social-media"
  | "live"
  | "government"
  | "forecast";
