import { type ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { readonly children: ReactNode }) {
  return (
    <div
      className={cn(
        "flex flex-col h-screen font-sans antialiased bg-white dark:bg-gray-950",
        fontSans.variable
      )}
    >
      {children}
    </div>
  );
}
