import { type ReactNode } from 'react'
import type { Metadata } from 'next'
import Link from 'next/link'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { readonly children: ReactNode }) {
  return <div className="flex flex-col h-screen bg-white dark:bg-gray-950">{children}</div>
}
